/**
  Standalone utilities that work without calling `.withLib` first.

  These functions have no nixpkgs dependency and use only Nix builtins.
*/
let
  collectInputsImpl = import ./collect-inputs.nix;
  flakeFormat = import ./format-flake.nix;

  /**
    Scan directories for `__inputs` declarations and collect them.

    Recursively scans .nix files for `__inputs` attribute declarations
    and merges them into a single attrset. Detects conflicts when the
    same input name has different definitions in different files.

    # Example

    ```nix
    imp.collectInputs ./outputs
    # => { treefmt-nix = { url = "github:numtide/treefmt-nix"; }; }
    ```

    # Arguments

    path
    : Directory or file path to scan for __inputs declarations.
  */
  collectInputs = collectInputsImpl;

  /**
    Convenience function combining collectInputs and formatFlake.

    Scans a directory for `__inputs` declarations and generates
    complete flake.nix content in one step.

    # Example

    ```nix
    imp.collectAndFormatFlake {
      src = ./outputs;
      coreInputs = { nixpkgs.url = "github:nixos/nixpkgs"; };
      description = "My flake";
    }
    # => "{ description = \"My flake\"; inputs = { ... }; ... }"
    ```

    # Arguments

    src
    : Directory to scan for __inputs declarations.

    coreInputs
    : Core flake inputs attrset (optional).

    description
    : Flake description string (optional).

    outputsFile
    : Path to outputs file (default: "./outputs.nix").

    header
    : Header comment for generated file (optional).
  */
  collectAndFormatFlake =
    {
      src,
      coreInputs ? { },
      description ? "",
      outputsFile ? "./outputs.nix",
      header ? "# Auto-generated by imp - DO NOT EDIT\n# Regenerate with: nix run .#imp-flake",
    }:
    let
      collectedInputs = collectInputs src;
    in
    flakeFormat.formatFlake {
      inherit
        description
        coreInputs
        collectedInputs
        outputsFile
        header
        ;
    };

  /**
    Build a registry from a directory structure.

    Scans a directory tree and builds a nested attrset mapping names to paths.
    Requires calling `.withLib` first to provide nixpkgs lib.

    # Example

    ```nix
    registry = (imp.withLib lib).registry ./nix
    # => { hosts.server = <path>; modules.nixos.base = <path>; ... }
    ```

    # Arguments

    path
    : Root directory path to scan for the registry.
  */
  registry = path: throw "imp.registry requires calling (imp.withLib lib).registry first";

in
{
  inherit
    collectInputs
    collectAndFormatFlake
    registry
    ;
}
